config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/posts'

resources :posts

root 'static_pages#home'

get '/about', to: 'static_pages#about', as: :about 

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
  
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
  
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end
  
def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path
end



  private

  def post_params
    params.require(:post).permit(:title, :author, :body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %> |
<%= link_to 'About', about_path %> |
<%= link_to 'Posts', posts_path %>

app/views/layouts/application.html.erb
<body>
<%= render 'layouts/navbar' %>
<%= yield %>

</body>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
<%= form_for @post do |f| %>
  <%= f.label :title %>: 
  <%= f.text_field :title %>

  <%= f.label :author %> 
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1> Posts </h1>
<p><%= link_to 'New Post', new_post_path %></p>
<% @posts.each do |post| %>
  <h2><%= post.title %></h2>
  <h3><%= post.author %></h3>
  <p><%= post.body %></p>
  <%= link_to 'Show post', post_path(post) %>
  <%= link_to 'Edit post', edit_post_path(post) %>
  <%= link_to 'Destroy post', post, method: :delete%>
<% end %>

app/views/posts/new.html.erb
<h1> New Post </h1>
<%= form_for @post do |f| %>
  <%= f.label :title %>: 
  <%= f.text_field :title %>

  <%= f.label :author %> 
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1> Post </h1>
<h2><%= @post.title %></h2>
<h3><%= @post.author %></h2>
<p><%= @post.body %></p>
<%= link_to 'Back', posts_path %>

app/views/static_pages/about.html.erb
<h1 style="text-align:center">What the hell is this</h1>
<p style="text-align:left">What the hell do you think it is? Buy something. Or get out.</p>

app/views/static_pages/home.html.erb
<h1 style="text-align:center"> Buy something or get out. </h1>
<p style="text-align:left">I guess you could sell something, too. Whatever, do something.</p>

app/views/static_pages/posts.html.erb
<h1 style="text-align:center">Shit for sale</h1>
<p>These things are for sale. Buy them.</p>